spring.application.name=GomsBook-AI-API
server.port=5001

management.endpoints.web.exposure.include=health,info,mappings
management.endpoint.health.show-details=always

# GomsBook AI
gomsbook.ai.ollama.base-url=http://localhost:11434
gomsbook.ai.ollama.chat-model=gemma4:31b-cloud
gomsbook.ai.ollama.embedding-model=nomic-embed-text


gomsbook.ai.project-root=C:/1004.GomsBook/03.Project/lunchwork_seoul
gomsbook.ai.publish-directory=C:/1004.GomsBook/02.Publish/lunchwork_seoul
gomsbook.ai.epubcheck.directory=D:/14.EPub/lib/epubcheck-5.3.0
gomsbook.ai.epubcheck.version=5.3.0